export const GET_PAITINGS = "GET_PAITINGS";
<<<<<<< HEAD
export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_PAINTINGS_BY_ARTIST = 'GET_PAINTINGS_BY_ARTIST';
export const GET_ARTIST_ID = 'GET_ARTIST_ID';
export const GET_OBRAID = 'GET_OBRAID';
export const GET_OBRAIDRANDON = 'GET_OBRAIDRANDON'
=======
export const SET_LOGIN = 'SET_LOGIN'
export const GET_OBRAID = 'GET_OBRAID';
export const GET_OBRAIDRANDON = 'GET_OBRAIDRANDON'
export const GET_REVIEWS = 'GET_REVIEWS'
>>>>>>> 5dfe96b2116919f73576a7a48225c49659a93062
